[book]
authors = ["breeze256"]
language = "en"
multilingual = false
src = "src"
title = "Plata for Hexo Documentation"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
mathjax-support = true